---
abstract: 'Compare web pages'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  LWP::UserAgent: 0
  Test::Fake::HTTPD: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Web-Compare
provides:
  Web::Compare:
    file: lib/Web/Compare.pm
    version: 0.01
requires:
  Carp: 0
  Class::Accessor::Lite: 0
  Diff::LibXDiff: 0
  Furl: 0
  HTTP::Request: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/bayashi/Web-Compare/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Web-Compare
version: 0.01
